name: Manual Maven Build and Artifact Upload

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - production
      run-tests:
        description: 'Run Tests'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests if chosen)
        run: mvn clean package -DskipTests=${{ github.event.inputs.run-tests == 'false' }}

      - name: Run tests (if enabled)
        if: ${{ github.event.inputs.run-tests == 'true' }}
        run: mvn test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app-${{ github.event.inputs.environment }}
          path: |
            target/*.jar
            target/*.war
          if-no-files-found: error
